name: CI

on:
  - push

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Xcode select
      run: |
        sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
    - name: Generating project
      run: swift package generate-xcodeproj
    - name: Testing
      run: |
        xcodebuild clean test -project Cacher.xcodeproj -scheme Cacher-Package -destination "platform=iOS Simulator,OS=13.0,name=iPhone 8"
